# saving directory
model_name: ResUNet
parent_dir: /home/haas/projects/def-haas/jsfung/
raw_path: "/home/haas/projects/def-haas/jsfung/Images/Raw/*.tif"
mask_path: "/home/haas/projects/def-haas/jsfung/Images/Mask/*.tif"
date: "September 5, 2022"

# Data/Patching Configs
DATASET:
  batch_size: 64
  lateral_steps: 64
  axial_steps: 16
  split_size: 0.8 # 80/20 - training/test
  AUGMENTATION:
    augment: True
    z_deg: 25 
    y_deg: 0
    x_deg: 0

# Model and Optimizer Settings
loss: dice_ce
weight: None

max_epochs: 1
dropout: 0.2
learning_rate: 0.00005
norm: batch

# Learning Rate Scheduler
end_cycle: 30

TRAINING:
  shuffle: True






