# saving directory
model_name: ResUNet
parent_dir: /home/haas/projects/def-haas/jsfung/
date: "August 21 2022"

# Data/Patching Configs
DATASET:
  batch_size: 64
  lateral_steps: 64
  axial_steps: 16
  split_size: 0.8 # 80/20 - training/test
  AUGMENTATION:
    augment: True
    z_deg: 25 
    y_deg: 0
    x_deg: 0

# Model and Optimizer Settings
loss: dice_ce
weights:

max_epochs: 75
dropout: 0.382
learning_rate: 0.000754
l2: 0.00421
norm: batch

# Learning Rate Scheduler
end_cycle: 30

TRAINING:
  shuffle: True






