# saving directory
model_name: ResUNet
parent_dir: /home/haas/projects/def-haas/jsfung
raw_path: "/home/jsfung/projects/def-haas/jsfung/Images/new_labels/Raw/*.tif"
mask_path: "/home/jsfung/projects/def-haas/jsfung/Images/new_labels/Mask/*.tif"
date: now

# Data/Patching Configs
DATASET:
  exp: '+s_+d_-f'
  batch_size: 64
  lateral_steps: 64
  axial_steps: 16
  z_patch: 16
  y_patch: 64
  x_patch: 64
  folds: 4 # 80/20 - training/test
  remove_artifacts: False
  artifacts: [7]
  ex_autofluorescence: False
  ex_melanocytes: True
  AUGMENTATION:
    augment: True
    z_deg: 25 
    y_deg: 0
    x_deg: 0
    gamma_lower: -0.5
    gamma_upper: 0.6
    mean_noise: 0.05
    std_noise: 0.025

# Model, Optimizer, Scheduler Settings
loss: dice_ce
weights:
max_epochs: 300
end_cycle: 1

MODEL:
  model_arch: UNET
  dropout: 0.10
  learning_rate: 7.54E-5
  l2: 0.00421
  norm: instance
  input_dim: 1
  channel_layers: [32, 64, 128, 256, 512]
  num_res_units: 2
  strides: [2,2,2,2]
  spatial_dim: 3

TRAINING:
  shuffle: True






